### ISSUE TITLE
ARM (is a thing, that exists)

### ISSUE THREAD

**Issue by blueForestIcarus** [terminusdb-labs/swipl-rs#34]
When compiling on arm (specifically aarch64-unknown-linux-gnu):
```
error[E0308]: mismatched types
   --> /var/lib/terminus/.cargo/registry/src/github.com-1ecc6299db9ec823/swipl-0.3.10/src/blob.rs:263:19
    |
263 |     result.name = name.as_ptr() as *mut i8;
    |     -----------   ^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |     |
    |     expected due to the type of this binding
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`
```

related: https://github.com/rust-lang/rust/issues/48633

**Comment by blueForestIcarus** [comment]
looking at the generated binding.rs:
```
pub struct PL_blob_t {
    pub magic: usize,
    pub flags: usize,
    pub name: *mut ::std::os::raw::c_char,
```

The type of name is actually std::os::raw::c_char, which on arm is equivalent to u8.

**Comment by matko** [comment]
ARM is definitely a thing that exists, and we should be supporting it properly.
I'll leave this issue open until we have an aarch test run in our CI to ensure that things keep building in the future. I think @rrooij is working on that right now.

**Comment by blueForestIcarus** [comment]
Note that for now, the fix wont automatically propagate to terminusdb because the repo specifies 0.3.10 for the swipl version.

**Comment by matko** [comment]
By now we've included ARM64 in all our CI pipelines and are even building a terminusdb docker container for arm64. So from now on this won't break anymore. I'm closing this issue.

Thanks a lot for your help!
