### ISSUE TITLE
A few rough edges

### ISSUE THREAD

**Issue by ThePuzzlemaker** [terminusdb-labs/swipl-rs#4]
This seems like a great library. But it has a few rough edges. I'm going to make this issue to document these. If you'd like me to split these into multiple issues, let me know.

## `term!` macro papercuts

- You cannot use quote notation for atoms.
- You cannot use cons-list notation for lists/a list + a non-nil tail
- You cannot use dynamic functor names

## Lack of a safe interface to ...

- Starting an engine/initializing SWIPL with a saved state. This would be as simple as a function like `Engine::with_saved_state(state: &[u8]) -> Engine`, that just calls `PL_set_resource_db_mem` *before* `PL_initialize`.
- `assertz`/`asserta` (through `PL_assert`). This one is not as important, in my opinion, but it is helpful to have a safe interface to assertions, without using queries which has extra baggage, both in terms of code, memory, and speed.
- Creating multiple term refs at once. SWIPL's FLI already provides functionality for this, and it's used quite a bit within internal code. I'm not quite sure why this shouldn't be exposed.
- Extraction of text that is *not* just atoms/strings. To, for example, get a string corresponding to the string that would be printed by `write/1`-ing a term (or `write_canonical/1`), you have to implement this yourself, or use a query and then get the result with `swipl::text` which is much less efficient.
- Unifying a term with a list with a non-nil tail directly. It is already possible to unify something with a list `&'a [T]` (where T is unifiable) into a cons-list e.g. `[A | [B | [C | [... | []]]]]`. But as far as I know, without using unsafe, it is not possible to unify something with a list and a non-nil tail e.g. `(&'a [T], Term<'a>)` into something like `[A | [B | [C | [... | Term]]]]`. This would be helpful as it means you do not have to reimplement list unification.
- Lack of a safe interface to `PL_chars_to_term`. Even if I wanted to construct a term using text only at runtime and parse it, I couldn't without reimplementing it myself as there is no safe interface to this function as far as I can tell.

## Making predicates (implemented in Prolog) at runtime could be easier.

This goes hand-in-hand with most of the other things I've mentioned here, as this is what sparked me to write my own interfaces on top of swipl-rs and swipl-sys to do these things. It is difficult to construct predicates (implemented in Prolog) at runtime without doing a bunch of manual (and fallible) unification, or by converting text to a term (which itself is fallible and is why I wanted to construct it programmatically in more of an AST-like format, and which itself does not have a safe interface). This is mostly because of papercuts in `term!` (due to lack of quote notation for atoms in functors as functor names only support identifiers, you can't use the neck operator `:-` to create a predicate with a clause).

**Comment by matko** [comment]
Hi there!

Thanks for your review of and interest in this crate. It definitely has a lot of rough edges, and I appreciate your feedback in this. I'll probably split this out into a bunch of separate issues over the next few days.

I agree with your points, and when I get time I'd like to get around to resolving some of this. Pull requests are welcome too.

Your ideas about run-time predicate generation are interesting and not something I had considered. If we had a good frontend for assert, and the papercuts in `term!` were resolved, would that be enough?

If you're doing any work on top of this library which you feel would be useful for a broader audience, don't be afraid to submit a pull request.

**Comment by matko** [comment]
I think I converted all your points into separate issues. If I missed anything, please let me know.

**Comment by ThePuzzlemaker** [comment]
> Your ideas about run-time predicate generation are interesting and not something I had considered. If we had a good frontend for assert, and the papercuts in `term!` were resolved, would that be enough?

Probably, yeah. I've been using this for mlatu-lang/mlatu#34 as a way to get a less fallible interface to SWIPL than text/stdio and a safer one than raw FFI.

**Comment by ThePuzzlemaker** [comment]
Closing as this was split into other issues.
