### ISSUE TITLE
swipl 9.2

### ISSUE THREAD

**Issue by matko** [terminusdb-labs/swipl-rs#56]
Here's an issue to keep track of the work remaining to have swipl-rs properly work with swipl.

#54 and #55 made sure the build works, and swipl-rs CI indicates no problem. However, when trying to run the tests in terminusdb, a lot of them fail. This could be due to a difference in swipl itself, but it could also be due to an issue in swipl-rs.

Once swipl-rs as a cause has been excluded I'll be releasing new versions of swipl-fli and swipl.

**Comment by morlic** [comment]
there's a few more places that need updating, context.rs and callable.rs. let me check in my fork.

**Comment by matko** [comment]
Issues were not related to swipl-rs,

I have released swipl-0.3.15 now, which supports both 9.0 and 9.2.
