### ISSUE TITLE
Clone Trait

### ISSUE THREAD

**Issue by flashpixx** [terminusdb-labs/swipl-rs#59]
Hello,

I'm would like to use swipl-rs in combination with [Axum](https://github.com/tokio-rs/axum), but to use Prolog in my Post / Get Routes I need a clonable trait, so is it possible that the Clone trait can be implemented especally for `Context<'static, ActivatedEngine<'static>>`

I try to use Arc and Rc, but this does not help

Thanks a lot

**Comment by matko** [comment]
Cloning a context is not a legitimate thing to do, and neither is using a context from several threads at once. This limitation is coming from swipl, and I've tried my best to make sure the types don't let you accidentally do it anyway. Glad to see that's working :).

If you want to work with swipl from several threads at the same time, create an engine per thread. You can even pass engines between threads, as long as you only activate them on one at a time, so one workflow could be where you just active an engine from a pool on demand. This can work as long as you never need to await while doing prolog.

If you need something more advanced, like a future that holds a prolog execution context in various states while potentially being passed between threads by a tasking system like tokio, unfortunately swipl-rs cannot do that today.
There's some ground work that has been done to support this use case in swipl: https://www.swi-prolog.org/pldoc/man?predicate=engine_yield/1 (and discussion thread: https://swi-prolog.discourse.group/t/yielding-prolog-engines-from-within-a-foreign-predicate/4806/22). I unfortunately never got around to making this work in swipl-rs. PRs are very welcome.

**Comment by flashpixx** [comment]
Some context for my question:

* I have got a prolog program for a web server (so asking for predicates)
* The fact-base will be filled once before the web server starts, so if query the prolog engine in my REST routes (read-only)
* It is impossible to generate for each HTTP call a new prolog engine within the route execution, because of complexity to generate the fact-base

**Comment by matko** [comment]
Creating a new engine does not mean you actually fully create a new prolog environment. Prolog engines are more like threads. They have their own stack, but they share the database with all other engines.

So if you already built your prolog database, any newly created engine will be able to see all that data.

**Comment by flashpixx** [comment]
This is exactly my use-case but in this case the clone trait is necessary, because Axum uses an extension for that, see https://docs.rs/axum/latest/axum/struct.Extension.html

**Comment by matko** [comment]
You don't need to pass around any state to get hold of a new engine. You can just call `Engine::new()` when you need a new engine. Prolog state is global to the entire process and not contained to any container object in swipl-rs.

**Comment by flashpixx** [comment]
I didn't understand it correctly, but in general:

1. in my main code I will do `initialize_swipl().unwrap().into()` and fill my data into the engine.
2. In my HTTP route I do `Engine::new()` but how can I get the context / EngineActivation?

The `initialize_swipl() -> Option<EngineActivation<'static>>` returns the Engine, this is nice, but if it is inialized it returns None, so it could be nice to get the existing instance.

This is my first Rust project, so maybe I didn't get all Rust details, thanks a lot for your help

**Comment by matko** [comment]
It sounds like you picked a fun rust project.

Don't use `initialize_swipl` for getting hold of an engine activation for your http routes. It's meant for cases where you only have one thread that you want to do some prolog on. In your case, you have several threads, through the tokio runtime.

See below snippet for how you'd get an engine, and then a context out of that engine:
```rust
let engine = Engine::new();
let activation = engine.activate();
let context: Context<_> = activation.into();
```
Just do this as part of your route where you need to run some prolog, and make sure you drop the activation (and context) before you do any await, or you'll likely get compiler errors.
