### ISSUE TITLE
Allow initializing swipl with a saved state

### ISSUE THREAD

**Issue by matko** [terminusdb-labs/swipl-rs#8]
Per #4, it'd be nice if we could initialize the swipl library with a saved state, pulling in its predicate definitions.

For extra super bonus points, it'd be even cooler if we could somehow embed a saved state in the built binary itself.

See also #3. Combining with ideas there, maybe as part of the build process, we could be parsing .pl files, auto-extracting rust-callable predicate definitions from them, and embedding a saved state of the compiled predicates into the resulting binary.

**Comment by ThePuzzlemaker** [comment]
You can build saved states with the swipl binary, so perhaps you could add a build script helper that builds a save state and puts it in OUT_DIR? Then it can just be included as bytes and passed as a &[u8]. See mlatu-lang/mlatu#34 for how I did this (src/prolog.rs and build.rs)
